version: "3"
services:
  backend:
    build: ./backend
    container_name: eyeseeu-backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: eyeseeu-frontend
    # ports:
      # - "3000:3000"  # Only for internal use
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx  # This sets the build context to the nginx directory
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
