version: "3"
services:
  backend:
    build: ./backend
    container_name: eyeseeu-backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: eyeseeu-frontend
    command: npm run build   # Ensures the frontend is built before nginx access
    networks:
      - app-network
    # You can optionally use volume to persist build outputs for nginx
    volumes:
      - ./frontend/build:/app/build

  nginx:
    build:
      context: ./nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
