version: "3"

services:
  backend:
    build: ./backend
    container_name: eyeseeu-backend
    ports:
      - "5000:5000"  # Backend API will be exposed on EC2 IP:5000 for internal access
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: eyeseeu-frontend
    # ports:
      # - "3000:3000"  # Only for internal use
    # depends_on:
      # - backend
    # restart: always
    restart: no
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"  # Exposes Nginx on port 80 for public access
    depends_on:
      # - frontend
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
